version: '3'

services:
    python:
        container_name: dev-python
        tty: true
        build:
            context: .
            dockerfile: python/Dockerfile
        volumes:
            - ../projects:/projects
        working_dir: /projects
volumes:
    projects:
